# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Vittra folkmusik
tagline:          'Vittror från tre landskap'
description:      'Folkmusik fiol kontrabas och sång'
url:              https://vittrafolkmusik.github.io
baseurl:          /vittrafolkmusik.github.io

author:
  name:           'Jonas Björkman'
  url:            https://cloud8.se

# paginate:         5

# Custom vars
version:          2.1.0
# gems: [jekyll-paginate]
gems:
  - jekyll-seo-tag

#github:
#  repo:           https://github.com/poole/hyde

social:
  name: Vittra folkmusik
  links:
    - https://www.facebook.com/Vittra-543481875853831/
    - https://soundcloud.com/vittra-3
    - https://www.youtube.com/channel/UCRLXiWxslt-oNdVMGvOWzRw