# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Trinning
tagline: "Alla goda ting är Trinning"
description: "Folkmusik fiol kontrabas och sång"
url: "https://trinning.se"
baseurl: ""

author:
  name: "Jonas Björkman"
  url: "https://cloud8.se"

# Custom vars
version: 2.1.0

social:
  name: Trinning folkmusik
  links:
    - https://www.facebook.com/Vittra-543481875853831/
    - https://soundcloud.com/vittra-3
    - https://www.youtube.com/channel/UCRLXiWxslt-oNdVMGvOWzRw
